/**
 * Maszyna 实例（id = maszyna）的侧边栏
 *
 * 用 autogenerated：往 docs/maszyna/ 里加文件即自动出现在侧边栏，
 * 顺序由 frontmatter 的 sidebar_position 控制。
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  maszyna: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
