/**
 * TPF2 实例（id = tpf2）的侧边栏
 *
 * 用 autogenerated：往 docs/tpf2/ 里加文件即自动出现在侧边栏，
 * 顺序由 frontmatter 的 sidebar_position 控制。
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  tpf2: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
